# AI-Powered Intelligent Hiring Assistant

## Notebook 3 : Resume Upload & Classification

### Objective

In this notebook we will build the core functionality of our AI Hiring Assistant.

Modules Covered:

- Load Trained ML Model
- Upload Resume
- Extract Resume Text
- Clean Resume
- Predict Resume Category

By the end of this notebook, the system will automatically identify the candidate's job profile from the uploaded resume.

In [17]:
# Install Required Libraries

!pip install pdfplumber
!pip install -q pdfplumber python-docx sentence-transformers spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20260107)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Using cached pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Requirement already satisfied: pypdfium2>=5.9.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.11.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20260107->pdfplumber) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20260107->pdfplumber) (49.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)
Using cached pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.5.0
    Uninstalling Pillow-9.5.0:
      Successfully uninstalled Pillow-9.5.0
Successfully installed Pillow-12.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 15.2 MB/s eta 0:00:00
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 44.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

### Explanation

We use **pdfplumber** to extract text from PDF resumes.

Most resumes are available in PDF format, so this library helps us read their content.

In [ ]:
import pandas as pd
import numpy as np

import joblib

import pdfplumber

import re

from IPython.display import display

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from config.py import API_KEY

In [19]:
classifier = joblib.load("resume_classifier.pkl")

tfidf = joblib.load("tfidf.pkl")

encoder = joblib.load("label_encoder.pkl")
print("Models Loaded Successfully")

Models Loaded Successfully

In [20]:
from google.colab import files

uploaded = files.upload()

Saving Devesh Sain Resume (1) (1).pdf to Devesh Sain Resume (1) (1) (1).pdf

In [21]:
resume_file = list(uploaded.keys())[0]

resume_text = ""

with pdfplumber.open(resume_file) as pdf:

    for page in pdf.pages:

         text = page.extract_text()

         if text:
           resume_text += text

WARNING:pdfminer.pdffont:Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
WARNING:pdfminer.pdffont:Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats

In [22]:
print(resume_text[:1500])

DEVESH SAIN
STUDENT AT JAIPUR ENGINEERING COLLEGE & RESEARCH CENTRE (JECRC)
📞 +91-9461950525 | 📧 saindevesh000@gmail.com | 🔗 LinkedIn: devesh-sain | 🔗 GitHub
SUMMARY
Motivated AI & Data Science undergraduate seeking opportunities to apply knowledge of machine
learning, data analysis, and programming to solve real-world problems while continuously enhancing
technical and analytical skills in a professional environment.
SKILLS
Languages: Python, Java,C++, SQL
Libraries/Frameworks: Scikit-learn, Pandas, NumPy, Matplotlib.
Tools & Platforms: Jupyter Notebook, VS Code, IBM Cloud.
Concepts: Machine Learning, Cloud technology, Data Analysis, Deep Learning.
Soft Skills: Analytical Thinking, Effective Team Collaboration, Time Management, Adaptive.
INTERNSHIPS
Jul 2025 – Aug 2025
AI and Cloud intern– Edunet Foundation
Explored cloud and AI concepts, architecture, and deployment strategies that power modern
digital transformation.
May 2026 - Present
Celebal Technologies Excellence Internship (CEI)
Practical Internship Focused on Real-World Project Development & Emerging Technologies
PROJECTS
1.Yuva Guide - AI Agent for Rural Youth Career Guidance
Personalized career advice based on skills, interest and education level.
Recommends government schemes,online courses,and training programs.
Multilingual support.
Cloud-hosted, lightweight,and scalable for rural adoption.
2.Aarogya X - AI-Based Antimicrobial Resistance Prediction Tool
The increasing misuse and overuse of antibiotics have led t

In [23]:
def clean_resume(text):

      text = re.sub(r"http\S+", " ", text)

      text = re.sub(r"www\S+", " ", text)

      text = re.sub(r"@\S+", " ", text)

      text = re.sub(r"[^A-Za-z ]", " ", text)

      text = re.sub(r"\s+", " ", text)

      return text.lower().strip()

In [24]:
clean_text = clean_resume(resume_text)

In [25]:
print(clean_text[:1000])

devesh sain student at jaipur engineering college research centre jecrc saindevesh linkedin devesh sain github summary motivated ai data science undergraduate seeking opportunities to apply knowledge of machine learning data analysis and programming to solve real world problems while continuously enhancing technical and analytical skills in a professional environment skills languages python java c sql libraries frameworks scikit learn pandas numpy matplotlib tools platforms jupyter notebook vs code ibm cloud concepts machine learning cloud technology data analysis deep learning soft skills analytical thinking effective team collaboration time management adaptive internships jul aug ai and cloud intern edunet foundation explored cloud and ai concepts architecture and deployment strategies that power modern digital transformation may present celebal technologies excellence internship cei practical internship focused on real world project development emerging technologies projects yuva gu

In [26]:
resume_vector = tfidf.transform([clean_text])

In [27]:
prediction = classifier.predict(resume_vector)

predicted_category = encoder.inverse_transform(prediction)

print("Predicted Category :")

print(predicted_category[0])

Predicted Category :
Data Science

In [28]:
print("Resume Successfully Classified.")

Resume Successfully Classified.

# Module 2 : Resume - Job Description Semantic Matching

## Objective

Traditional keyword matching is not enough because two resumes can use different words
while having the same meaning.

To solve this problem, we use **Sentence Transformers**.

Sentence Transformers convert complete sentences into dense numerical vectors (embeddings).

Then we calculate the **Cosine Similarity** between the Resume and Job Description.

Higher similarity means better match.

In [31]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding Model Loaded Successfully")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding Model Loaded Successfully

In [32]:
resume_embedding = embedding_model.encode(clean_text)

In [33]:
resume_embedding.shape

(384,)

In [34]:
from google.colab import files

print("Upload Job Description")

uploaded_jd = files.upload()

Upload Job Description

Saving data_scientist JD.pdf to data_scientist JD.pdf

In [35]:
jd_file = list(uploaded_jd.keys())[0]

In [36]:
if jd_file.endswith(".pdf"):

      jd_text = ""

      with pdfplumber.open(jd_file) as pdf:

           for page in pdf.pages:

                  text = page.extract_text()

                  if text:
                      jd_text += text

                  elif jd_file.endswith(".txt"):

                        with open(jd_file, "r", encoding="utf-8") as file:

                                jd_text = file.read()

                  else:

                        print("Unsupported File Format")

In [37]:
print(jd_text[:1500])

Data Scientist
Job Description
Overview:
We are looking for a talented and experienced Data Scientist to join our dynamic team. As a Data
Scientist, you will leverage your analytical skills and expertise in machine learning to extract insights from
complex datasets and drive data-driven decision-making across our organization. You will collaborate
closely with cross-functional teams to develop predictive models, uncover actionable insights, and solve
challenging business problems.
Responsibilities
Data Analysis and Exploration
• Analyze large, complex datasets to identify trends, patterns, and relationships.
• Conduct exploratory data analysis (EDA) to gain insights and formulate hypotheses.
• Utilize statistical methods and data visualization techniques to communicate findings effectively.
Predictive Modeling and Machine Learning
• Develop and deploy predictive models using machine learning algorithms.
• Perform feature engineering, model selection, and hyperparameter tuning to optimize model
performance.
• Evaluate model accuracy, precision, recall, and other performance metrics.
Data Mining and Pattern Recognition
• Apply data mining techniques to extract actionable insights from structured and unstructured
data.
• Identify patterns and anomalies in data to detect fraud, predict customer behavior, or optimize
business processes.
• Implement clustering, classification, regression, and other machine learning algorithms as
needed.
Experimentation and A/B Testing
• Design and

In [38]:
clean_jd = clean_resume(jd_text)

In [39]:
jd_embedding = embedding_model.encode(clean_jd)

In [40]:
jd_embedding.shape

(384,)

##Calculate Cosine Similarity

In [41]:
similarity = cosine_similarity([resume_embedding],[jd_embedding])

In [42]:
print(similarity)

[[0.4426555]]

In [43]:
match_score = float(similarity[0][0] * 100)

In [44]:
print(f"Resume Match Score : {match_score:.2f}%")

Resume Match Score : 44.27%

In [45]:
if match_score >= 85:
      level = "Excellent Match"

elif match_score >= 70:
    level = "Good Match"

elif match_score >= 50:
    level = "Average Match"

else:
    level = "Poor Match"

print(level)

Poor Match

In [46]:
print("="*60)

print("Predicted Category :", predicted_category[0])

print("Resume Match Score :", round(match_score,2),"%")

print("Match Quality :", level)

print("="*60)

============================================================
Predicted Category : Data Science
Resume Match Score : 44.27 %
Match Quality : Poor Match
============================================================

# Module 3 : Skill Gap Analysis

## Objective

Matching percentage alone is not enough.

The recruiter also wants to know:

- Which skills are already present?
- Which skills are missing?
- What should the candidate learn?

This module compares the Resume and Job Description skills.

In [47]:
import re

In [ ]:
skills_database = [


    # Programming Languages
    "Python", "Java", "C", "C++", "C#", "JavaScript", "TypeScript",
    "R", "Go", "Rust", "PHP", "Kotlin", "Swift",

    # Web Development
    "HTML", "CSS", "Bootstrap", "Tailwind CSS",
    "React", "Angular", "Vue", "Next.js",
    "Node.js", "Express", "Django", "Flask", "FastAPI",
    "Spring", "Hibernate", ".NET", "ASP.NET",

    # Databases
    "SQL", "MySQL", "PostgreSQL", "MongoDB",
    "SQLite", "Oracle", "Redis", "NoSQL",

    # Data Science & ML
    "Machine Learning", "Deep Learning", "NLP",
    "Computer Vision", "CV",
    "Scikit-Learn", "TensorFlow", "Keras",
    "PyTorch", "XGBoost", "LightGBM",

    # Python Libraries
    "NumPy", "Pandas", "Matplotlib",
    "Seaborn", "SciPy", "OpenCV",

    # Big Data
    "Spark", "PySpark", "Hadoop",
    "Hive", "Kafka",

    # Cloud
    "AWS", "Azure", "GCP",
    "EC2", "S3", "Lambda",

    # DevOps
    "Docker", "Kubernetes",
    "Jenkins", "Git", "GitHub",
    "GitLab", "Linux", "Bash",

    # GenAI
    "OpenAI", "LLM", "RAG",
    "LangChain", "LlamaIndex",
    "Transformers", "Hugging Face",
    "FAISS", "ChromaDB",
    "Prompt Engineering",

    # Visualization
    "Power BI", "Tableau",
    "Excel", "Looker",

    # Mobile
    "Android", "Flutter",
    "React Native",

    # Testing
    "JUnit", "Selenium",
    "PyTest", "Unit Testing",

    # Networking & Security
    "Cyber Security",
    "Network Security",
    "Penetration Testing",

    # Software Engineering
    "Agile", "Scrum",
    "Project Management",
    "System Design",
    "REST API",
    "Microservices",

    # Soft Skills
    "Communication",
    "Leadership",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Time Management",
    "Presentation Skills",
    "Analytical Thinking"
]

In [49]:
import re

def extract_skills(text):

    # Lowercase
        text = text.lower()

    # Replace special characters with space
        text = re.sub(r"[^a-z0-9#+.-]", " ", text)

     # Remove extra spaces
        text = re.sub(r"\s+", " ", text)

        found_skills = set()

        for skill in skills_database:

                skill_lower = skill.lower()


                skill_pattern = re.sub(r"[^a-z0-9#+.-]", " ", skill_lower)

                if skill_pattern in text:

                             found_skills.add(skill)

        return sorted(found_skills)

In [50]:
resume_skills = extract_skills(clean_text)

print(resume_skills)

['deep learning', 'excel', 'git', 'github', 'java', 'machine learning', 'matplotlib', 'numpy', 'pandas', 'python', 'sql']

In [51]:
jd_skills = extract_skills(clean_jd)

print(jd_skills)

['communication', 'excel', 'machine learning', 'matplotlib', 'problem solving', 'python', 'pytorch', 'rag', 'tableau', 'tensorflow']

In [52]:
matched_skills = list(
      set(resume_skills).intersection(jd_skills)
      )

matched_skills = sorted(matched_skills)

print(matched_skills)

['excel', 'machine learning', 'matplotlib', 'python']

In [53]:
missing_skills = list(
      set(jd_skills).difference(resume_skills)
      )

missing_skills = sorted(missing_skills)

print(missing_skills)

['communication', 'problem solving', 'pytorch', 'rag', 'tableau', 'tensorflow']

In [54]:
extra_skills = list(
      set(resume_skills).difference(jd_skills)
      )

extra_skills = sorted(extra_skills)

print(extra_skills)

['deep learning', 'git', 'github', 'java', 'numpy', 'pandas', 'sql']

In [55]:
if len(jd_skills)==0:

      skill_match=0

else:

      skill_match=(len(matched_skills)/len(jd_skills))*100

      print(f"Skill Match : {skill_match:.2f}%")

Skill Match : 40.00%

In [56]:
print("="*60)

print("Matched Skills")

for skill in matched_skills:

    print("✔",skill)

    print()

print("Missing Skills")

for skill in missing_skills:

        print("❌",skill)

        print()

print("Additional Skills")

for skill in extra_skills:

        print("⭐",skill)

        print()

print(f"Skill Match : {skill_match:.2f}%")

print("="*60)

============================================================
Matched Skills
✔ excel

✔ machine learning

✔ matplotlib

✔ python

Missing Skills
❌ communication

❌ problem solving

❌ pytorch

❌ rag

❌ tableau

❌ tensorflow

Additional Skills
⭐ deep learning

⭐ git

⭐ github

⭐ java

⭐ numpy

⭐ pandas

⭐ sql

Skill Match : 40.00%
============================================================

In [57]:
# Install Required Libraries

#!pip install -q spacy
#!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [59]:
#import pandas as pd

#skills_df = pd.read_csv("skills.csv")

In [60]:
#print(skills_df.shape)

(0, 1249)

In [61]:
#skills_list = list(skills_df.columns)

#skills_list.remove("technical skills")

In [62]:
#print("Total Skills :", len(skills_list))

Total Skills : 1248

In [63]:
#skills_list[:30]

['ajenti',
 'django-suit',
 'django-xadmin',
 'flask-admin',
 'flower',
 'grappelli',
 'wooey',
 'algorithms',
 'pypattyrn',
 'python-patterns',
 'sortedcontainers',
 'django-simple-captcha',
 'django-simple-spam-blocker',
 'django-compressor',
 'django-pipeline',
 'django-storages',
 'fanstatic',
 'fileconveyor',
 'flask-assets',
 'jinja-assets-compressor',
 'webassets',
 'audiolazy',
 'audioread',
 'beets',
 'dejavu',
 'django-elastic-transcoder',
 'eyed3',
 'id3reader',
 'm3u8',
 'mingus']

In [64]:
#import spacy
#from spacy.matcher import PhraseMatcher

#nlp = spacy.load("en_core_web_sm")

In [65]:
#matcher = PhraseMatcher(
      #nlp.vocab,
          #attr="LOWER"
          #)

In [66]:
#patterns = []

#for skill in skills_list:

    #patterns.append(
            #nlp.make_doc(skill)
               # )

#matcher.add("SKILLS",patterns)

In [67]:
"""def extract_skills(text):

      doc = nlp(text)

      matches = matcher(doc)

      extracted = set()

      for match_id,start,end in matches:

              extracted.add(doc[start:end].text)

      return sorted(extracted)"""

In [68]:
"""resume_skills = extract_skills(clean_text)

print("Resume Skills")

print(resume_skills)"""

Resume Skills
['ai', 'analysis', 'analytical', 'analytical skills', 'architecture', 'c', 'cloud', 'data analysis', 'engineering', 'github', 'healthcare', 'ibm', 'java', 'jupyter', 'machine learning', 'matplotlib', 'numpy', 'pandas', 'programming', 'python', 'reports', 'research', 'sql', 'technical', 'time management', 'training']

In [69]:
"""jd_skills = extract_skills(clean_jd)

print("JD Skills")

print(jd_skills)"""

JD Skills
['algorithms', 'analysis', 'analytical', 'analytical skills', 'analytics', 'analyze', 'business stakeholders', 'communication', 'computer science', 'cross functional', 'data analysis', 'datasets', 'design', 'economics', 'engineering', 'experimental', 'experiments', 'ggplot', 'hypothesis', 'machine learning', 'mathematics', 'matplotlib', 'metrics', 'mining', 'modeling', 'pattern', 'performance metrics', 'predictive analytics', 'programming', 'python', 'pytorch', 'r', 'statistical analysis', 'statistics', 'tableau', 'technical', 'tensorflow', 'testing']

In [70]:
"""matched_skills = list(
        set(resume_skills).intersection(jd_skills)
              )

matched_skills = sorted(matched_skills)

print(matched_skills)
"""

['analysis', 'analytical', 'analytical skills', 'data analysis', 'engineering', 'machine learning', 'matplotlib', 'programming', 'python', 'technical']

In [71]:
"""missing_skills = list(
        set(jd_skills).difference(resume_skills)
              )

missing_skills = sorted(missing_skills)

print(missing_skills)
"""

['algorithms', 'analytics', 'analyze', 'business stakeholders', 'communication', 'computer science', 'cross functional', 'datasets', 'design', 'economics', 'experimental', 'experiments', 'ggplot', 'hypothesis', 'mathematics', 'metrics', 'mining', 'modeling', 'pattern', 'performance metrics', 'predictive analytics', 'pytorch', 'r', 'statistical analysis', 'statistics', 'tableau', 'tensorflow', 'testing']

In [72]:
"""extra_skills = list(
        set(resume_skills).difference(jd_skills)
              )

extra_skills = sorted(extra_skills)

print(extra_skills)"""

['ai', 'architecture', 'c', 'cloud', 'github', 'healthcare', 'ibm', 'java', 'jupyter', 'numpy', 'pandas', 'reports', 'research', 'sql', 'time management', 'training']

In [73]:
"""
if len(jd_skills)==0:

        skill_match=0

else:

     skill_match=(len(matched_skills)/len(jd_skills))*100

     print(f"Skill Match : {skill_match:.2f}%")"""

Skill Match : 26.32%

In [74]:
"""
print("="*60)

print("Matched Skills")

for skill in matched_skills:

    print("✔",skill)

    print()

print("Missing Skills")

for skill in missing_skills:

    print("❌",skill)

    print()

print("Additional Skills")

for skill in extra_skills:

         print("⭐",skill)

         print()

print(f"Skill Match : {skill_match:.2f}%")

print("="*60)"""

============================================================
Matched Skills
✔ analysis

✔ analytical

✔ analytical skills

✔ data analysis

✔ engineering

✔ machine learning

✔ matplotlib

✔ programming

✔ python

✔ technical

Missing Skills
❌ algorithms

❌ analytics

❌ analyze

❌ business stakeholders

❌ communication

❌ computer science

❌ cross functional

❌ datasets

❌ design

❌ economics

❌ experimental

❌ experiments

❌ ggplot

❌ hypothesis

❌ mathematics

❌ metrics

❌ mining

❌ modeling

❌ pattern

❌ performance metrics

❌ predictive analytics

❌ pytorch

❌ r

❌ statistical analysis

❌ statistics

❌ tableau

❌ tensorflow

❌ testing

Additional Skills
⭐ ai

⭐ architecture

⭐ c

⭐ cloud

⭐ github

⭐ healthcare

⭐ ibm

⭐ java

⭐ jupyter

⭐ numpy

⭐ pandas

⭐ reports

⭐ research

⭐ sql

⭐ time management

⭐ training

Skill Match : 26.32%
============================================================

In [75]:
matched = len(matched_skills)
required = len(jd_skills)

skill_match = (matched / required) * 100

In [84]:
final_score = (0.7 * similarity + 0.3 * skill_match)

In [82]:
print(f"Final Candidate Score : {final_score}%")

Final Candidate Score : [[8.204596]]%

In [85]:
if final_score >= 90:

      recommendation = "Excellent Candidate ⭐"

elif final_score >= 80:

      recommendation = "Highly Recommended ✅"

elif final_score >= 70:

      recommendation = "Recommended 👍"

elif final_score >= 60:

      recommendation = "Consider After Upskilling 📘"

else:

  recommendation = "Not Recommended ❌"

print(recommendation)

Not Recommended ❌

In [90]:
print("\n")
print("="*70)
print("FINAL CANDIDATE REPORT")
print("="*70)

print(f"Predicted Category      : {predicted_category}")

print(f"Similarity              : {similarity}%")

print(f"Skill Match             : {skill_match}%")

print(f"Final Candidate Score   : {final_score}%")

print(f"Hiring Recommendation   : {recommendation}")

print(f"Matched Skills          : {len(matched_skills)}")

print(f"Missing Skills          : {len(missing_skills)}")

print("="*70)

======================================================================
FINAL CANDIDATE REPORT
======================================================================
Predicted Category      : ['Data Science']
Similarity              : [[0.4426555]]%
Skill Match             : 26.31578947368421%
Final Candidate Score   : [[8.204596]]%
Hiring Recommendation   : Not Recommended ❌
Matched Skills          : 10
Missing Skills          : 28
======================================================================

#🟢Load Knowledge Base

In [94]:
knowledge_df = pd.read_csv("knowledge_base (2).csv")

knowledge_df.head()

,Skill,Category,Description,Importance,Learning Resource,Interview Tip,Difficulty
0,Acob,Languages,Acob is an important technology used in the fi...,High,https://www.google.com/search?q=Learn+Acob,Build projects using Acob and prepare intervie...,Medium
1,Actionscript,Languages,Actionscript is an important technology used i...,High,https://www.google.com/search?q=Learn+Actionsc...,Build projects using Actionscript and prepare ...,Medium
2,Acu-Cobol,Languages,Acu-Cobol is an important technology used in t...,High,https://www.google.com/search?q=Learn+Acu-Cobol,Build projects using Acu-Cobol and prepare int...,Medium
3,Ada,Languages,Ada is an important technology used in the fie...,High,https://www.google.com/search?q=Learn+Ada,Build projects using Ada and prepare interview...,Medium
4,Adaplex,Languages,Adaplex is an important technology used in the...,High,https://www.google.com/search?q=Learn+Adaplex,Build projects using Adaplex and prepare inter...,Medium

In [95]:
print(missing_skills)

['algorithms', 'analytics', 'analyze', 'business stakeholders', 'communication', 'computer science', 'cross functional', 'datasets', 'design', 'economics', 'experimental', 'experiments', 'ggplot', 'hypothesis', 'mathematics', 'metrics', 'mining', 'modeling', 'pattern', 'performance metrics', 'predictive analytics', 'pytorch', 'r', 'statistical analysis', 'statistics', 'tableau', 'tensorflow', 'testing']

In [96]:
retrieved_data = []

for skill in missing_skills:

    rows = knowledge_df[
            knowledge_df["Skill"].str.lower()
                    ==
                            skill.lower()
                                ]
    if len(rows) > 0:

         retrieved_data.append(rows.iloc[0])

In [97]:
retrieved_df = pd.DataFrame(retrieved_data)

retrieved_df

,Skill,Category,Description,Importance,Learning Resource,Interview Tip,Difficulty
1733,Pytorch,Development Tools,Pytorch is an important technology used in the...,Medium,https://www.google.com/search?q=Learn+Pytorch,Build projects using Pytorch and prepare inter...,Medium
162,R,Languages,R is an important technology used in the field...,High,https://www.google.com/search?q=Learn+R,Build projects using R and prepare interview q...,Medium
3872,Tableau,Business And Office Support Applications,Tableau is an important technology used in the...,Medium,https://www.google.com/search?q=Learn+Tableau,Build projects using Tableau and prepare inter...,Medium
1885,Tensorflow,Development Tools,Tensorflow is an important technology used in ...,Medium,https://www.google.com/search?q=Learn+Tensorflow,Build projects using Tensorflow and prepare in...,Medium

In [98]:
context = ""

for _, row in retrieved_df.iterrows():

    context += f"""

    Skill : {row['Skill']}

    Description :

    {row['Description']}

    Importance :

    {row['Importance']}

    Learning Resource :

    {row['Learning Resource']}

    Interview Tip :

    {row['Interview Tip']}

    Difficulty :

    {row['Difficulty']}

    ---------------------------------------

    """

In [99]:
print(context)

    Skill : Pytorch

    Description :

    Pytorch is an important technology used in the field of Development Tools. It is commonly used in software development and enterprise projects.

    Importance :

    Medium

    Learning Resource :

    https://www.google.com/search?q=Learn+Pytorch

    Interview Tip :

    Build projects using Pytorch and prepare interview questions.

    Difficulty :

    Medium

    ---------------------------------------



    Skill : R

    Description :

    R is an important technology used in the field of Languages. It is commonly used in software development and enterprise projects.

    Importance :

    High

    Learning Resource :

    https://www.google.com/search?q=Learn+R

    Interview Tip :

    Build projects using R and prepare interview questions.

    Difficulty :

    Medium

    ---------------------------------------



    Skill : Tableau

    Description :

    Tableau is an important technology used in the field of Business And Office Support Applications. It is commonly used in software development and enterprise projects.

    Importance :

    Medium

    Learning Resource :

    https://www.google.com/search?q=Learn+Tableau

    Interview Tip :

    Build projects using Tableau and prepare interview questions.

    Difficulty :

    Medium

    ---------------------------------------



    Skill : Tensorflow

    Description :

    Tensorflow is an important technology used in the field of Development Tools. It is commonly used in software development and enterprise projects.

    Importance :

    Medium

    Learning Resource :

    https://www.google.com/search?q=Learn+Tensorflow

    Interview Tip :

    Build projects using Tensorflow and prepare interview questions.

    Difficulty :

    Medium

    ---------------------------------------

In [117]:
!pip install -q openai

In [118]:
from openai import OpenAI

In [ ]:
client = OpenAI(

      api_key=API_KEY,

          base_url="https://openrouter.ai/api/v1"

          )

In [125]:
response = client.chat.completions.create(

      model="meta-llama/llama-3.1-8b-instruct",

          messages=[

                  {

                      "role":"user",

                      "content":"Say Hello"

                                        }
  ])

print(response.choices[0].message.content)

Hello! How are you today? Is there something I can help you with or would you like to chat?

In [129]:
similarity_percentage = float(similarity) * 100

/tmp/ipykernel_474/2782397220.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  similarity_percentage = float(similarity) * 100

In [130]:
prompt = f"""
You are an experienced HR Recruiter and Technical Interviewer.

Analyze the following candidate.

Candidate Category:
{predicted_category}

Resume Similarity:
{similarity_percentage:.2f}%

Skill Match:
{skill_match:.2f}%

Matched Skills:
{', '.join(matched_skills)}

Missing Skills:
{', '.join(missing_skills)}

Retrieved Knowledge:
{context}

Generate a professional report with these headings:

1. Candidate Summary
2. Strengths
3. Weaknesses
4. Explanation of Missing Skills
5. Personalized Learning Roadmap
6. Interview Preparation Tips
7. Hiring Recommendation

Keep the report professional and easy to understand.
"""

In [131]:
response = client.chat.completions.create(

      model="meta-llama/llama-3.1-8b-instruct",

          messages=[
                  {
                              "role":"user",
                                          "content":prompt
                                                  }
                                                      ],

                                                          temperature=0.4,

                                                              max_tokens=700

                                                              )

ai_feedback = response.choices[0].message.content

print(ai_feedback)

**Candidate Report**

**Candidate Summary**

The candidate is a Data Science professional with a moderate level of similarity to the job requirements (44.27%) and skill match (26.32%). They have listed skills such as analysis, analytical, machine learning, and programming, but are missing several key skills required for the position.

**Strengths**

1. **Basic Data Analysis Skills**: The candidate has listed skills such as analysis, analytical, and data analysis, indicating a basic understanding of data analysis concepts.
2. **Programming Skills**: They have listed Python as one of their skills, which is a common programming language used in data science.
3. **Machine Learning Knowledge**: The candidate has listed machine learning as one of their skills, indicating a basic understanding of machine learning concepts.

**Weaknesses**

1. **Lack of Key Skills**: The candidate is missing several key skills required for the position, including algorithms, business stakeholders, communication, computer science, cross-functional, datasets, design, economics, experimental, experiments, ggplot, hypothesis, mathematics, metrics, mining, modeling, pattern, performance metrics, predictive analytics, and statistics.
2. **Limited Technical Skills**: The candidate's technical skills are limited to basic data analysis and machine learning concepts, with no advanced technical skills listed.
3. **No Business Acumen**: The candidate has not listed any business-related skills, such as communication, business stakeholders, or economics, which are essential for a data science role.

**Explanation of Missing Skills**

The candidate is missing several key skills required for the position, including:

* Algorithms: The candidate has not listed any algorithms-related skills, which are essential for data science roles.
* Business stakeholders: The candidate has not listed any business-related skills, which are essential for data science roles.
* Communication: The candidate has not listed any communication-related skills, which are essential for data science roles.
* Computer science: The candidate has not listed any computer science-related skills, which are essential for data science roles.
* Cross-functional: The candidate has not listed any cross-functional skills, which are essential for data science roles.
* Datasets: The candidate has not listed any datasets-related skills, which are essential for data science roles.
* Design: The candidate has not listed any design-related skills, which are essential for data science roles.
* Economics: The candidate has not listed any economics-related skills, which are essential for data science roles.
* Experimental: The candidate has not listed any experimental-related skills, which are essential for data science roles.
* Experiments: The candidate has not listed any experiments-related skills, which are essential for data science roles.
* Ggplot: The candidate has not listed any ggplot-related skills, which are essential for data science roles.
* Hypothesis: The candidate has not listed any hypothesis-related skills, which are essential for data science roles.
* Mathematics: The candidate has not listed any mathematics-related skills, which are essential for data science roles.
* Metrics: The candidate has not listed any metrics-related skills, which are essential for data science roles.
* Mining: The candidate has not listed any mining-related skills, which are essential for data science roles.
* Modeling: The candidate has not listed any modeling-related skills, which are essential for data science roles.
* Pattern: The candidate has not listed any pattern-related skills, which are essential for data science roles.
* Performance metrics: The candidate has not listed any performance metrics-related skills,

In [132]:
with open("AI_Feedback.txt","w",encoding="utf-8") as f:
      f.write(ai_feedback)

      print("Feedback Saved Successfully")

Feedback Saved Successfully